version: '3'


services:
  emqx:
    image: emqx:5.6.1     #imagen de DOkcer que se utilizará para el servicio
    container_name: emqx  #nombre del contenedor
    environment:          #creacion de variables de entorno para configurar el servicio
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"   #nombre del nodo EMQX
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"   #estrategia de descubrimiento de clúster EMQX
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"   #nodos semilla del clúster EMQX
    healthcheck:  #comprobación de salud del contenedor
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s  #intervalo entre comprobaciones
      timeout: 25s  #tiempo maximo de espera para una comprobacion de salud
      retries: 5    #intentos de comprobación de salud
    networks:     #configuración de red
      emqx-bridge:
        aliases:
        - node1.emqx.io
    ports:      #mapeo de puertos
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 

#
  node-red:
    image: nodered/node-red:latest
    container_name:  nodered
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data:/data

networks: #definicion de redes
  emqx-bridge:
    driver: bridge
  node-red-net:
    driver: bridge